export const idTemplate = {
  name: 'id',
  type: 'text',
  content: 'Type Something...',
  position: {
    x: 155,
    y: 39.29,
  },
  width: 45,
  height: 10,
  rotate: 0,
  alignment: 'right',
  verticalAlignment: 'top',
  fontSize: 18,
  lineHeight: 1,
  characterSpacing: 0,
  fontColor: '#000000',
  backgroundColor: '',
  opacity: 1,
  strikethrough: false,
  underline: false,
  required: false,
  readOnly: false,
};
