export const titleTemplate = {
  name: 'title',
  type: 'text',
  content: 'Invoice',
  position: {
    x: 140.72,
    y: 20,
  },
  width: 58.49,
  height: 21.11,
  rotate: 0,
  alignment: 'right',
  verticalAlignment: 'top',
  fontSize: 36,
  lineHeight: 1,
  characterSpacing: 0,
  fontColor: '#000000',
  backgroundColor: '',
  opacity: 1,
  strikethrough: false,
  underline: false,
  required: false,
  readOnly: false,
  fontName: 'NotoSerifJP-Regular',
} as const;
